### ISSUE TITLE
requires::operator=

### ISSUE THREAD

**Issue by Lunderberg** [ArtificialEvolvingWorld/Entendre#3]
Right now, `requires::operator=` calls `exit(0)` unconditionally.  Is this a function that should never be used?  If so, lets mark it with `= delete` instead, so it causes a compile-time error rather than a runtime error.

**Comment by csullivan** [comment]
Thanks, wasn't meant to be in the main repository. Removed in 2a6c9f90765df3e886ba71eea39b812486c661d6.
