### ISSUE TITLE
Population::Reproduce memory leak

### ISSUE THREAD

**Issue by Lunderberg** [ArtificialEvolvingWorld/Entendre#5]
In `Population::Reproduce`, there is a call to `Genome* child = new Genome`, with no corresponding call to `delete`.  Looking at it, we could change it to being declared on the stack without any issue.

**Comment by csullivan** [comment]
Thanks for the review, agreed, it's a temporary and should be on the stack. Fixed in 06d75a033a17a0abfe9989a7becb2b394b20ae42.
